-- This product includes software derived from the project "datahub-dine" by SAP SE.
-- Copyright © SAP SE. Licensed under the Apache License, Version 2.0.
-- The original software is available at: https://github.com/SAP-samples/datahub-dine/blob/main/data/reviews.csv
-- Modifications:
-- This is a modified version of the original work.
-- Changes include:
-- - Reformatted and adapted SQL assets for Microsoft SQL Server
-- - Adjusted schema definitions, data types, and scripts
-- - Minor structural changes for instructional and educational use
-- These modifications are not affiliated with, nor endorsed by, SAP SE.


CREATE TABLE tblReviews
(ID int NOT NULL,
Category varchar(1000),
ProductName varchar(1000),
Review varchar(8000),
CONSTRAINT PK_tblReviews PRIMARY KEY CLUSTERED (ID));
INSERT INTO tblReviews(ID, Category, ProductName, Review) VALUES 
(1, 'Notebooks', 'Notebook Basic 15', 'Three start. I have some issues like some keys don''t work on first instance..and is somewhat slow also'),
(2, 'Notebooks', 'Notebook Basic 17', 'Heating and not wake up. Check twice when buy it on Offer.'),
(3, 'Notebooks', 'Notebook Basic 18', '2nd hand laptops!!! The laptop I received already had an user on it with password etc. These are not new laptops!'),
(4, 'Notebooks', 'Notebook Basic 19', 'BEST LAPTOP IN A PRICE SEGMENT OF Rs 55-60K.'),
(5, 'Notebooks', 'Notebook Professional 15', 'second hand product. don''t buy this. It is used. battery power is low. stand by power is only 4 hour.'),
(6, 'Handhelds', 'Easy Hand III', 'very bad. My product is not working what do I do ? I have paid everything! This is very very bad .'),
(7, 'Flat screens', 'Ergo Screen', 'waste of money. Battery is draining out very quickly after 2-3 hours of usage. Also it''s not lasting for more than 7 days once it''s in a sleep mode.Not at all recommend.'),
(8, 'Handhelds', '1UMTS PDA', 'Very bad product. The Serial number on the product and the serial number on the laptop are different.'),
(9, 'Laser printers', 'Laser Professional Eco', 'One star. Trackpad not working... tried 2 contact amazon.. not picking'),
(10, 'Ink jet printers', 'Deskjet Super Color', 'two star.Returned looking for Mac pro.'),
(11, 'Notebooks', 'Notebook Basic 15', 'Three star. very low memory. Not good buy.'),
(12, 'Notebooks', 'Notebook Basic 17', 'Bad product. Battery issue with the laptop. Doesn''t give backup as expected . Really upset with the product.'),
(13, 'Notebooks', 'Notebook Basic 18', 'not a good product. charger not working after week use'),
(14, 'Notebooks', 'Notebook Basic 19', 'better laptop is available in this price segment.'),
(15, 'Notebooks', 'Notebook Professional 15', ' have had extremely bad experiences with Apple products. they suffer from a chronic problem which is well known : overheating'),
(16, 'Handhelds', 'Easy Hand III', 'Worst display.. fonts are blurry.. best part is help less amazon care. saying that there is no return policy..'),
(17, 'Flat screens', 'Ergo Screen', 'Itâ€™s been just 2 months and the device has already stopped functioning. It doesnâ€™t turn on. I need a replacement. â€™m very angry and disappointed.'),
(18, 'Handhelds', '1UMTS PDA', 'Very bad product. The mac book delivered is not at all working this is not expected from such a reputed brand .looking for an immediate replacement or return.'),
(19, 'Laser printers', 'Laser Professional Eco', 'Fake Product. received A Laptop Without Serial number of screen. unable To Claim Warranty.'),
(20, 'Ink jet printers', 'Deskjet Super Color', 'Pathetic product. Below standard quality.'),
(21, 'Notebooks', 'Notebook Basic 15', 'Price mismatch. never buying such things on amazon ever again'),
(22, 'Notebooks', 'Notebook Basic 17', 'very poor. disappointed. Defective product.'),
(23, 'Notebooks', 'Notebook Basic 18', 'Be super careful about the NO COST EMI offer. The step is not shown. I paid the amount and now Kotak refuses to convert my purchase into EMI'),
(24, 'Notebooks', 'Notebook Basic 19', 'Not good product -: After 6 months it became turn off. It is not starting now.'),
(25, 'Notebooks', 'Notebook Professional 15', 'Not worthy of 2017 model in 55k bcs before 4 months in sale cut price of 10 k now no discount..only making fool on name of great indian sale'),
(26, 'Handhelds', 'Easy Hand III', 'Amazon late delivery as usual and had so pathetic experience with Amazon courier team this time.'),
(27, 'Flat screens', 'Ergo Screen', 'Overpriced people don''t know slot about laptop.Apple products will cost u a lot cuz of its compatibility.'),
(28, 'Handhelds', '1UMTS PDA', 'Worst laptop ever not for student use I repeat not for students.'),
(29, 'Laser printers', 'Laser Professional Eco', 'Price is very high not worthy'),
(30, 'Ink jet printers', 'Deskjet Super Color', 'bad product. Compatible issue for Microsoft office files. not better than window platform.'),
(31, 'Notebooks', 'Notebook Basic 15', 'Bad Service.After 1 month it doesn''t start without any problem and then i have to change main power IC.That become very costly.'),
(32, 'Notebooks', 'Notebook Basic 17', 'Bad. Received a broken/opened package. most likely a returned package.'),
(33, 'Notebooks', 'Notebook Basic 18', 'pathetic. Wheel is not working well. Wheel is also very hard to press (to open the link in new window)... Now I use the wheel just to scroll. Usage of wheel as an alternate of Open in New Window is much difficult.'),
(34, 'Notebooks', 'Notebook Basic 19', 'small in size. so grip in your palm will not be very comfortable.otherwise good product.'),
(35, 'Notebooks', 'Notebook Professional 15', 'Not able to hold it properly in hand and wire is also too short. I recommend to buy other larger size mouse with slightly more cost'),
(36, 'Handhelds', 'Easy Hand III', 'very bad. The mouse is small for my palm. It is difficult to click. especially double clicks. The click buttons are not very responsive.'),
(37, 'Flat screens', 'Ergo Screen', 'Defective product. not able to print a single page. Carriage struck in the sides of the printer loudly. Now I have to contact HP service. Very painful process'),
(38, 'Handhelds', '1UMTS PDA', 'Very expensive. Cartridge is very expensive....not recommended to buy this product .'),
(39, 'Laser printers', 'Laser Professional Eco', 'Average product. too bad for pc users.'),
(40, 'Ink jet printers', 'Deskjet Super Color', 'Utterly useless printer... TOTALLY unexpected from HP.. Pages getting stuck repeatedly. cartridge issues. abnormal noise.. Not worth even at 90% discount.'),
(41, 'Handhelds', 'Easy Hand III', 'starsExcellent Product and Service by Amazon and Seller.'),
(42, 'Flat screens', 'Ergo Screen', 'starsGood product but not able to login to Facetime.'),
(43, 'Handhelds', '1UMTS PDA', 'Very good product. Perfectly packed & delivered on time. Working good till now.'),
(44, 'Laser printers', 'Laser Professional Eco', 'One of the Best MacBook from Apple. Thanks to Amazon for fastest delivery and very Competetive Price.'),
(45, 'Ink jet printers', 'Deskjet Super Color', 'There is no comparison for apple product. Performance is beyond expectation. Customer service is awesome!! loved it.'),
(46, 'Notebooks', 'Notebook Basic 15', 'Works great sound is clear and is really loud. Would recommend'),
(47, 'Notebooks', 'Notebook Basic 17', 'This is a awesome product. My husband and I love it.'),
(48, 'Notebooks', 'Notebook Basic 18', 'Love the sound that comes out and Alexa is very informative!'),
(49, 'Notebooks', 'Notebook Basic 19', 'great device to listen to music.best blue tooth on the market today.I highly recommend it'),
(50, 'Notebooks', 'Notebook Professional 15', 'Excellent product at this price.The performance n battery life is superb for the whole day.Best buy. these days you don''t get a compact good performing laptop at this price.'),
(51, 'Handhelds', 'Easy Hand III', 'As everyone knows any Apple product is outstanding and superior to the rest. Its superb. fast and amazing.I recommend buying the AirCase MacBook sleeve ( black and green ) and the MOCA smooth touch battle hard shell skin cover ( grey colour ). Both these products are on amazon.in. both VERY GOOD and must buy products to help improve your MacBook Air experience. ( I do not advertise or sell these products btw)'),
(52, 'Flat screens', 'Ergo Screen', 'The product is what it is and there is nothing to review about its capabilities. I wanted a MacBook and after looking at multiple outlets for prices amazon had the best pricing for this product. (With offers combined).I ordered the product on prime and there was a deficit on stock and by that delayed my delivery by a couple of days. Other than that the product was as expected. Delivery was smooth and as expected. The retailer is Appario retail and to my knowledge is an amazon subsidiary.'),
(53, 'Handhelds', '1UMTS PDA', 'Nice Product! Have been using it since for last 3 months now. No issues faced.'),
(54, 'Laser printers', 'Laser Professional Eco', 'Its really amazing. Exactly the same experience which I heard and described.Macbook air is really best and affordable to all in broad range of costly apple products...!!'),
(55, 'Ink jet printers', 'Deskjet Super Color', 'TSimply amazing! The best ever battery backup! High performance. And not to forget amazon packing and safety for your product is incredible. Love the way they care for your product by the time it reach safe in your hands.'),
(56, 'Notebooks', 'Notebook Basic 15', 'Got it safe.....when i ordered i was tensed as ....i thgt it might have cracks....but amazing product....thanku apple...thanku .....amazon....thnku for the best courier service'),
(57, 'Notebooks', 'Notebook Basic 17', 'Don''t want to mention anything for apple MAC book :) Super product'),
(58, 'Notebooks', 'Notebook Basic 18', 'Always apple is the best product.build quality and software works together.u canâ€™t use this one for media purposes.its one time investment for office use.'),
(59, 'Notebooks', 'Notebook Basic 19', 'its a amazing product for a normal user....amazon had a good packing also'),
(60, 'Notebooks', 'Notebook Professional 15', 'excellent product with good exchange price... I like product and service'),
(61, 'Handhelds', 'Easy Hand III', 'What a fine piece of design and engineering! If you can get this. DO GET IT.'),
(62, 'Flat screens', 'Ergo Screen', 'warranty details are fine upgraded to high Sierra performing well.. not using it heavily but yes Best Buy for the price. Will update again after usage'),
(63, 'Handhelds', '1UMTS PDA', 'All works fine. No issues or defects till now. Its nearly more than a month from purchase. Nice packaging. Perfectly planned delivery.'),
(64, 'Laser printers', 'Laser Professional Eco', 'Loving it so far...1 star less because the capslock key is a little defective...doesn''t press at once.'),
(65, 'Ink jet printers', 'Deskjet Super Color', 'was looking for a light laptop for multimedia use. perfect travel companion. as I was already using iOS ecosystem. was nt tough to shift from windows to apple.'),
(66, 'Notebooks', 'Notebook Basic 15', 'Best rate got from market value for money great quality'),
(67, 'Notebooks', 'Notebook Basic 17', 'Not much to be said. apple is always great in quality and the look and feel!!'),
(68, 'Notebooks', 'Notebook Basic 18', '10/10......the best laptop in world. apple products are amazing. you will never regret it buying.'),
(69, 'Notebooks', 'Notebook Basic 19', 'Fast Processor & user friendly Amazing Battery life !'),
(70, 'Notebooks', 'Notebook Professional 15', 'Very good and light weight laptop. This is a perfect choice for bloggers. Excellent battery life.'),
(71, 'Handhelds', 'Easy Hand III', 'MacBook..nothing to say. I have been using it since last 4 months.'),
(72, 'Flat screens', 'Ergo Screen', 'Great product. timeless design but flawless. Apple has been best at making things which do what they are suppose to without much fuss and pomp'),
(73, 'Handhelds', '1UMTS PDA', 'Best decision I have ever made. Good purchase.'),
(74, 'Laser printers', 'Laser Professional Eco', 'Am happy that I switch from Windows to Mac'),
(75, 'Ink jet printers', 'Deskjet Super Color', 'First time using Apple product. Amazing experience. Loved it'),
(76, 'Notebooks', 'Notebook Basic 15', 'Its a fantastic machine. very smooth touchpad. fine keyboard and awesome performance. Now I will never switch to windows and thanks Amazon for giving too much discount.'),
(77, 'Notebooks', 'Notebook Basic 17', 'Great product as usual from apple. I ordered it for my wife. and she is loving it :-)'),
(78, 'Notebooks', 'Notebook Basic 18', 'Very good product. Perfectly packed & delivered on time. Working good till now.'),
(79, 'Notebooks', 'Notebook Basic 19', 'One of the Best MacBook from Apple. Thanks to Amazon for fastest delivery and very Competetive Price.'),
(80, 'Notebooks', 'Notebook Professional 15', 'The Mac was good but the mouse pad are not wrking properly'),
(81, 'Handhelds', 'Easy Hand III', 'Good product. But we are not getting on line support for any operation issue in macbook.'),
(82, 'Flat screens', 'Ergo Screen', 'Finally a MacBook possession. Worth every penny. A must have for all those who can afford. Got it in 50k in Diwali sale'),
(83, 'Handhelds', '1UMTS PDA', 'Really good is and it is very smooth everything works great but stuff like display and design must be updated.'),
(84, 'Laser printers', 'Laser Professional Eco', 'Amazing product by Apple and great delivery by Amazon. Kudos to both'),
(85, 'Ink jet printers', 'Deskjet Super Color', 'Excellent product and good delivery turnaround time by Amazon'),
(86, 'Notebooks', 'Notebook Basic 15', 'Decent performance for daily tasks but the screen brightness could be better.'),
(87, 'Notebooks', 'Notebook Basic 17', 'System feels sturdy, however boot time is slightly longer than expected.'),
(88, 'Notebooks', 'Notebook Basic 18', 'Average laptop. Works fine for office use but not suitable for heavy multitasking.'),
(89, 'Notebooks', 'Notebook Basic 19', 'Good design and finish, but speakers are not very loud.'),
(90, 'Notebooks', 'Notebook Professional 15', 'Strong performance overall, although the device heats up during long usage.'),
(91, 'Handhelds', 'Easy Hand III', 'Product quality is acceptable, but the UI feels outdated in comparison to others.'),
(92, 'Handhelds', '1UMTS PDA', 'Battery life is reasonable, but charging time is quite slow.'),
(93, 'Handhelds', 'Easy Hand III', 'Comfortable to hold and lightweight, yet responsiveness sometimes lags.'),
(94, 'Handhelds', '1UMTS PDA', 'Good build quality, but software updates are very infrequent.'),
(95, 'Flat screens', 'Ergo Screen', 'Picture clarity is good, but viewing angles are limited.'),
(96, 'Flat screens', 'Ergo Screen', 'Stylish design and slim profile, though stand feels slightly unstable.'),
(97, 'Laser printers', 'Laser Professional Eco', 'Print quality is sharp, but initial setup was confusing.'),
(98, 'Laser printers', 'Laser Professional Eco', 'Works well for home use, however toner replacement is expensive.'),
(99, 'Laser printers', 'Laser Professional Eco', 'Fast printing speed, but wireless connectivity drops occasionally.'),
(100, 'Ink jet printers', 'Deskjet Super Color', 'Print colors are vibrant, but ink drains faster than expected.'),
(101, 'Ink jet printers', 'Deskjet Super Color', 'Easy to install and use, yet paper jams occur now and then.'),
(102, 'Ink jet printers', 'Deskjet Super Color', 'Suitable for basic printing needs, not recommended for bulk printing.'),
(103, 'Notebooks', 'Notebook Basic 15', 'Keyboard is comfortable to type on, but trackpad accuracy needs improvement.'),
(104, 'Notebooks', 'Notebook Basic 17', 'Good value for money, though fan noise is noticeable under load.'),
(105, 'Notebooks', 'Notebook Professional 15', 'Solid laptop with reliable performance, but slightly overpriced.'),
(106, 'Notebooks', 'Notebook Professional 15', 'This review is intentionally extensive and detailed to support testing of long-text storage, indexing behavior, full-text search, analytics pipelines, and instructional demonstrations within Microsoft SQL Server environments. I have been using the Notebook Professional 15 extensively in a variety of real-world scenarios, including software development, data analysis, documentation writing, virtual meetings, and light multimedia work. Over several months of daily use, this device has revealed both its strengths and its limitations, making it a suitable candidate for an in-depth evaluation rather than a brief star-based review. From a build-quality perspective, the chassis feels sturdy and well-finished. There is minimal flex in the keyboard deck, and the hinge mechanism holds the display firmly in place without wobble, even when opened and closed multiple times a day. The overall design is understated and professional, making it appropriate for both office and personal environments. While it is not the lightest notebook in its class, the balance between weight and durability is reasonable, especially for users who prioritize reliability over ultra-portability. Performance has generally been consistent under typical workloads. For daily productivity tasks such as web browsing, spreadsheet manipulation, code editing, and document preparation, the system performs smoothly with no major slowdowns. Application launch times are acceptable, and multitasking with several browser tabs and background processes is handled competently. However, under sustained heavy workloads—such as long-running data processing jobs or extended video encoding—the device tends to warm up noticeably. Thermal management appears adequate but not exceptional, and users may experience increased fan noise during prolonged high CPU usage. The keyboard is comfortable for long typing sessions, offering decent key travel and tactile feedback. As someone who writes and codes extensively, this was an important factor for me, and it did not disappoint. The trackpad is generally accurate, though there were occasional instances where multi-touch gestures were not registered on the first attempt. While this did not significantly hinder daily use, it is an area where refinement would be welcome in future revisions. Battery life is one of the more positive aspects of this notebook. Under mixed usage—including Wi‑Fi browsing, document editing, and periodic video playback—the device reliably lasts through a full workday. Standby performance is also respectable, with minimal battery drain overnight. Fast charging support is a practical convenience, allowing the battery to regain a meaningful charge level during short breaks. Display quality is acceptable for professional use. Text appears sharp, and color reproduction is sufficient for general tasks, though it may not satisfy users engaged in color-critical creative work. Brightness levels are adequate for indoor environments but can struggle slightly under direct sunlight. Viewing angles are stable, and eye strain during extended usage has not been a significant issue for me. Audio output is serviceable but unremarkable. The built-in speakers are clear enough for video calls and casual media consumption, but they lack depth and volume for immersive listening experiences. Most users will prefer external speakers or headphones for extended media usage. In terms of connectivity, the Notebook Professional 15 includes a practical selection of ports that cover most day-to-day needs without immediate reliance on adapters. Wireless connectivity has been stable overall, with only rare interruptions. Bluetooth performance has been consistent with peripheral devices such as keyboards, mice, and headphones. Software stability has been good, and system updates have not caused any major issues so far. Boot times are reasonable, and system recovery features function as expected. That said, bundled software could be reduced, as some preinstalled applications add little value and may marginally impact performance for users who prefer a minimal setup. Overall, this notebook represents a solid, if not groundbreaking, option in its category. It does not attempt to be the thinnest, flashiest, or most powerful device available, but instead delivers dependable performance, good battery life, and acceptable build quality for professional and everyday use. Users looking for a reliable workhorse rather than a premium luxury device will likely find it meets their expectations. While there is room for improvement—particularly in thermal efficiency, trackpad responsiveness, and audio quality—the Notebook Professional 15 remains a competent and practical choice for its intended audience. This unusually long review is deliberately verbose to exceed typical review lengths and to support technical scenarios such as large text handling, NLP processing, sentiment analysis at scale, full-text indexing demonstrations, and data warehousing exercises. In real-world consumer platforms, reviews of this length are uncommon; however, from a data and instructional standpoint, they are extremely useful.');