/*
Deployment script for DP800Free

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "DP800Free"
:setvar DefaultFilePrefix "DP800Free"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
/*
The column [dbo].[tblTest].[Notes] is being dropped, data loss could occur.

The column Description on table [dbo].[tblTest] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The type for column Description in table [dbo].[tblTest] is currently  NVARCHAR (200) NULL but is being changed to  NVARCHAR (101) NOT NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  NVARCHAR (101) NOT NULL.
*/

IF EXISTS (select top 1 1 from [dbo].[tblTest])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [Graph].[FreindsOf] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [Graph].[FreindsOf])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [Graph].[Student] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [Graph].[Student])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [Graph].[TaughtBy] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [Graph].[TaughtBy])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [Graph].[Teacher] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [Graph].[Teacher])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [SalesLT].[SalesOrderDetail] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [SalesLT].[SalesOrderDetail])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [SalesLT].[Product] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [SalesLT].[Product])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [SalesLT].[SalesOrderHeader] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [SalesLT].[SalesOrderHeader])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [SalesLT].[ProductCategory] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [SalesLT].[ProductCategory])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [SalesLT].[ProductModelProductDescription] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [SalesLT].[ProductModelProductDescription])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [SalesLT].[Customer] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [SalesLT].[Customer])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [SalesLT].[ProductModel] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [SalesLT].[ProductModel])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [SalesLT].[CustomerAddress] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [SalesLT].[CustomerAddress])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [SalesLT].[Address] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [SalesLT].[Address])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [SalesLT].[ProductDescription] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [SalesLT].[ProductDescription])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [School].[PupilsCopy] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [School].[PupilsCopy])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [School].[MSSQL_TemporalHistoryFor_573245097] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [School].[MSSQL_TemporalHistoryFor_573245097])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [School].[Scores] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [School].[Scores])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [School].[PupilsCopy2] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [School].[PupilsCopy2])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [School].[ScoresCopy] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [School].[ScoresCopy])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [School].[Pupils] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [School].[Pupils])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [School].[Scores4] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [School].[Scores4])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [School].[PupilFriends] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [School].[PupilFriends])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[BuildVersion] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[BuildVersion])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[ErrorLog] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[ErrorLog])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_SalesOrderHeader_OrderID]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [DF_SalesOrderHeader_OrderID];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_SalesOrderDetail_rowguid]...';


GO
ALTER TABLE [SalesLT].[SalesOrderDetail] DROP CONSTRAINT [DF_SalesOrderDetail_rowguid];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_SalesOrderDetail_UnitPriceDiscount]...';


GO
ALTER TABLE [SalesLT].[SalesOrderDetail] DROP CONSTRAINT [DF_SalesOrderDetail_UnitPriceDiscount];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_SalesOrderDetail_ModifiedDate]...';


GO
ALTER TABLE [SalesLT].[SalesOrderDetail] DROP CONSTRAINT [DF_SalesOrderDetail_ModifiedDate];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_Product_rowguid]...';


GO
ALTER TABLE [SalesLT].[Product] DROP CONSTRAINT [DF_Product_rowguid];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_Product_ModifiedDate]...';


GO
ALTER TABLE [SalesLT].[Product] DROP CONSTRAINT [DF_Product_ModifiedDate];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_SalesOrderHeader_RevisionNumber]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [DF_SalesOrderHeader_RevisionNumber];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_SalesOrderHeader_Freight]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [DF_SalesOrderHeader_Freight];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_SalesOrderHeader_OrderDate]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [DF_SalesOrderHeader_OrderDate];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_SalesOrderHeader_TaxAmt]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [DF_SalesOrderHeader_TaxAmt];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_SalesOrderHeader_rowguid]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [DF_SalesOrderHeader_rowguid];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_SalesOrderHeader_ModifiedDate]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [DF_SalesOrderHeader_ModifiedDate];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_SalesOrderHeader_Status]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [DF_SalesOrderHeader_Status];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_SalesOrderHeader_SubTotal]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [DF_SalesOrderHeader_SubTotal];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_SalesOrderHeader_OnlineOrderFlag]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [DF_SalesOrderHeader_OnlineOrderFlag];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_ProductCategory_ModifiedDate]...';


GO
ALTER TABLE [SalesLT].[ProductCategory] DROP CONSTRAINT [DF_ProductCategory_ModifiedDate];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_ProductCategory_rowguid]...';


GO
ALTER TABLE [SalesLT].[ProductCategory] DROP CONSTRAINT [DF_ProductCategory_rowguid];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_ProductModelProductDescription_ModifiedDate]...';


GO
ALTER TABLE [SalesLT].[ProductModelProductDescription] DROP CONSTRAINT [DF_ProductModelProductDescription_ModifiedDate];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_ProductModelProductDescription_rowguid]...';


GO
ALTER TABLE [SalesLT].[ProductModelProductDescription] DROP CONSTRAINT [DF_ProductModelProductDescription_rowguid];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_Customer_rowguid]...';


GO
ALTER TABLE [SalesLT].[Customer] DROP CONSTRAINT [DF_Customer_rowguid];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_Customer_NameStyle]...';


GO
ALTER TABLE [SalesLT].[Customer] DROP CONSTRAINT [DF_Customer_NameStyle];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_Customer_ModifiedDate]...';


GO
ALTER TABLE [SalesLT].[Customer] DROP CONSTRAINT [DF_Customer_ModifiedDate];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_ProductModel_ModifiedDate]...';


GO
ALTER TABLE [SalesLT].[ProductModel] DROP CONSTRAINT [DF_ProductModel_ModifiedDate];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_ProductModel_rowguid]...';


GO
ALTER TABLE [SalesLT].[ProductModel] DROP CONSTRAINT [DF_ProductModel_rowguid];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_CustomerAddress_rowguid]...';


GO
ALTER TABLE [SalesLT].[CustomerAddress] DROP CONSTRAINT [DF_CustomerAddress_rowguid];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_CustomerAddress_ModifiedDate]...';


GO
ALTER TABLE [SalesLT].[CustomerAddress] DROP CONSTRAINT [DF_CustomerAddress_ModifiedDate];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_Address_rowguid]...';


GO
ALTER TABLE [SalesLT].[Address] DROP CONSTRAINT [DF_Address_rowguid];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_Address_ModifiedDate]...';


GO
ALTER TABLE [SalesLT].[Address] DROP CONSTRAINT [DF_Address_ModifiedDate];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_ProductDescription_ModifiedDate]...';


GO
ALTER TABLE [SalesLT].[ProductDescription] DROP CONSTRAINT [DF_ProductDescription_ModifiedDate];


GO
PRINT N'Dropping Default Constraint [SalesLT].[DF_ProductDescription_rowguid]...';


GO
ALTER TABLE [SalesLT].[ProductDescription] DROP CONSTRAINT [DF_ProductDescription_rowguid];


GO
PRINT N'Dropping Default Constraint [School].[DK_ScoresCopy_PupilID]...';


GO
ALTER TABLE [School].[ScoresCopy] DROP CONSTRAINT [DK_ScoresCopy_PupilID];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_BuildVersion_ModifiedDate]...';


GO
ALTER TABLE [dbo].[BuildVersion] DROP CONSTRAINT [DF_BuildVersion_ModifiedDate];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_ErrorLog_ErrorTime]...';


GO
ALTER TABLE [dbo].[ErrorLog] DROP CONSTRAINT [DF_ErrorLog_ErrorTime];


GO
PRINT N'Dropping Foreign Key [SalesLT].[FK_SalesOrderDetail_Product_ProductID]...';


GO
ALTER TABLE [SalesLT].[SalesOrderDetail] DROP CONSTRAINT [FK_SalesOrderDetail_Product_ProductID];


GO
PRINT N'Dropping Foreign Key [SalesLT].[FK_SalesOrderDetail_SalesOrderHeader_SalesOrderID]...';


GO
ALTER TABLE [SalesLT].[SalesOrderDetail] DROP CONSTRAINT [FK_SalesOrderDetail_SalesOrderHeader_SalesOrderID];


GO
PRINT N'Dropping Foreign Key [SalesLT].[FK_ProductCategory_ProductCategory_ParentProductCategoryID_ProductCategoryID]...';


GO
ALTER TABLE [SalesLT].[ProductCategory] DROP CONSTRAINT [FK_ProductCategory_ProductCategory_ParentProductCategoryID_ProductCategoryID];


GO
PRINT N'Dropping Foreign Key [SalesLT].[FK_Product_ProductCategory_ProductCategoryID]...';


GO
ALTER TABLE [SalesLT].[Product] DROP CONSTRAINT [FK_Product_ProductCategory_ProductCategoryID];


GO
PRINT N'Dropping Foreign Key [SalesLT].[FK_SalesOrderHeader_Customer_CustomerID]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [FK_SalesOrderHeader_Customer_CustomerID];


GO
PRINT N'Dropping Foreign Key [SalesLT].[FK_CustomerAddress_Customer_CustomerID]...';


GO
ALTER TABLE [SalesLT].[CustomerAddress] DROP CONSTRAINT [FK_CustomerAddress_Customer_CustomerID];


GO
PRINT N'Dropping Foreign Key [SalesLT].[FK_Product_ProductModel_ProductModelID]...';


GO
ALTER TABLE [SalesLT].[Product] DROP CONSTRAINT [FK_Product_ProductModel_ProductModelID];


GO
PRINT N'Dropping Foreign Key [SalesLT].[FK_ProductModelProductDescription_ProductModel_ProductModelID]...';


GO
ALTER TABLE [SalesLT].[ProductModelProductDescription] DROP CONSTRAINT [FK_ProductModelProductDescription_ProductModel_ProductModelID];


GO
PRINT N'Dropping Foreign Key [SalesLT].[FK_SalesOrderHeader_Address_ShipTo_AddressID]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [FK_SalesOrderHeader_Address_ShipTo_AddressID];


GO
PRINT N'Dropping Foreign Key [SalesLT].[FK_CustomerAddress_Address_AddressID]...';


GO
ALTER TABLE [SalesLT].[CustomerAddress] DROP CONSTRAINT [FK_CustomerAddress_Address_AddressID];


GO
PRINT N'Dropping Foreign Key [SalesLT].[FK_SalesOrderHeader_Address_BillTo_AddressID]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [FK_SalesOrderHeader_Address_BillTo_AddressID];


GO
PRINT N'Dropping Foreign Key [SalesLT].[FK_ProductModelProductDescription_ProductDescription_ProductDescriptionID]...';


GO
ALTER TABLE [SalesLT].[ProductModelProductDescription] DROP CONSTRAINT [FK_ProductModelProductDescription_ProductDescription_ProductDescriptionID];


GO
PRINT N'Dropping Foreign Key [School].[FK_ScoresCopy_PupilsCopy]...';


GO
ALTER TABLE [School].[ScoresCopy] DROP CONSTRAINT [FK_ScoresCopy_PupilsCopy];


GO
PRINT N'Dropping Check Constraint [SalesLT].[CK_SalesOrderDetail_OrderQty]...';


GO
ALTER TABLE [SalesLT].[SalesOrderDetail] DROP CONSTRAINT [CK_SalesOrderDetail_OrderQty];


GO
PRINT N'Dropping Check Constraint [SalesLT].[CK_SalesOrderDetail_UnitPrice]...';


GO
ALTER TABLE [SalesLT].[SalesOrderDetail] DROP CONSTRAINT [CK_SalesOrderDetail_UnitPrice];


GO
PRINT N'Dropping Check Constraint [SalesLT].[CK_SalesOrderDetail_UnitPriceDiscount]...';


GO
ALTER TABLE [SalesLT].[SalesOrderDetail] DROP CONSTRAINT [CK_SalesOrderDetail_UnitPriceDiscount];


GO
PRINT N'Dropping Check Constraint [SalesLT].[CK_Product_ListPrice]...';


GO
ALTER TABLE [SalesLT].[Product] DROP CONSTRAINT [CK_Product_ListPrice];


GO
PRINT N'Dropping Check Constraint [SalesLT].[CK_Product_StandardCost]...';


GO
ALTER TABLE [SalesLT].[Product] DROP CONSTRAINT [CK_Product_StandardCost];


GO
PRINT N'Dropping Check Constraint [SalesLT].[CK_Product_Weight]...';


GO
ALTER TABLE [SalesLT].[Product] DROP CONSTRAINT [CK_Product_Weight];


GO
PRINT N'Dropping Check Constraint [SalesLT].[CK_Product_SellEndDate]...';


GO
ALTER TABLE [SalesLT].[Product] DROP CONSTRAINT [CK_Product_SellEndDate];


GO
PRINT N'Dropping Check Constraint [SalesLT].[CK_SalesOrderHeader_ShipDate]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [CK_SalesOrderHeader_ShipDate];


GO
PRINT N'Dropping Check Constraint [SalesLT].[CK_SalesOrderHeader_DueDate]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [CK_SalesOrderHeader_DueDate];


GO
PRINT N'Dropping Check Constraint [SalesLT].[CK_SalesOrderHeader_Freight]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [CK_SalesOrderHeader_Freight];


GO
PRINT N'Dropping Check Constraint [SalesLT].[CK_SalesOrderHeader_Status]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [CK_SalesOrderHeader_Status];


GO
PRINT N'Dropping Check Constraint [SalesLT].[CK_SalesOrderHeader_SubTotal]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [CK_SalesOrderHeader_SubTotal];


GO
PRINT N'Dropping Check Constraint [SalesLT].[CK_SalesOrderHeader_TaxAmt]...';


GO
ALTER TABLE [SalesLT].[SalesOrderHeader] DROP CONSTRAINT [CK_SalesOrderHeader_TaxAmt];


GO
PRINT N'Dropping Table [Graph].[FreindsOf]...';


GO
DROP TABLE [Graph].[FreindsOf];


GO
PRINT N'Dropping Table [Graph].[Student]...';


GO
DROP TABLE [Graph].[Student];


GO
PRINT N'Dropping Table [Graph].[TaughtBy]...';


GO
DROP TABLE [Graph].[TaughtBy];


GO
PRINT N'Dropping Table [Graph].[Teacher]...';


GO
DROP TABLE [Graph].[Teacher];


GO
PRINT N'Dropping Table [SalesLT].[SalesOrderDetail]...';


GO
DROP TABLE [SalesLT].[SalesOrderDetail];


GO
PRINT N'Dropping Table [SalesLT].[SalesOrderHeader]...';


GO
DROP TABLE [SalesLT].[SalesOrderHeader];


GO
PRINT N'Dropping Table [SalesLT].[CustomerAddress]...';


GO
DROP TABLE [SalesLT].[CustomerAddress];


GO
PRINT N'Dropping Table [SalesLT].[Address]...';


GO
DROP TABLE [SalesLT].[Address];


GO
PRINT N'Dropping Table [School].[PupilsCopy]...';


GO
DROP TABLE [School].[PupilsCopy];


GO
PRINT N'Dropping Table [School].[MSSQL_TemporalHistoryFor_573245097]...';


GO
DROP TABLE [School].[MSSQL_TemporalHistoryFor_573245097];


GO
PRINT N'Dropping Table [School].[PupilsCopy2]...';


GO
DROP TABLE [School].[PupilsCopy2];


GO
PRINT N'Dropping Table [School].[ScoresCopy]...';


GO
DROP TABLE [School].[ScoresCopy];


GO
PRINT N'Dropping Table [School].[Scores4]...';


GO
DROP TABLE [School].[Scores4];


GO
PRINT N'Dropping Table [School].[PupilFriends]...';


GO
DROP TABLE [School].[PupilFriends];


GO
PRINT N'Dropping Table [dbo].[BuildVersion]...';


GO
DROP TABLE [dbo].[BuildVersion];


GO
PRINT N'Dropping Function [School].[fnGetPupilName]...';


GO
DROP FUNCTION [School].[fnGetPupilName];


GO
PRINT N'Dropping Function [dbo].[ufnGetSalesOrderStatusText]...';


GO
DROP FUNCTION [dbo].[ufnGetSalesOrderStatusText];


GO
PRINT N'Dropping Function [School].[fnGetScores]...';


GO
DROP FUNCTION [School].[fnGetScores];


GO
PRINT N'Dropping Function [dbo].[ufnGetCustomerInformation]...';


GO
DROP FUNCTION [dbo].[ufnGetCustomerInformation];


GO
PRINT N'Dropping Table [SalesLT].[Customer]...';


GO
DROP TABLE [SalesLT].[Customer];


GO
PRINT N'Dropping Function [School].[fnGetPupilScores]...';


GO
DROP FUNCTION [School].[fnGetPupilScores];


GO
PRINT N'Dropping Function [dbo].[ufnGetAllCategories]...';


GO
DROP FUNCTION [dbo].[ufnGetAllCategories];


GO
PRINT N'Dropping Index [SalesLT].[vProductAndDescription].[IX_vProductAndDescription]...';


GO
DROP INDEX [IX_vProductAndDescription]
    ON [SalesLT].[vProductAndDescription];


GO
PRINT N'Dropping View [SalesLT].[vProductAndDescription]...';


GO
DROP VIEW [SalesLT].[vProductAndDescription];


GO
PRINT N'Dropping View [SalesLT].[vGetAllCategories]...';


GO
DROP VIEW [SalesLT].[vGetAllCategories];


GO
PRINT N'Dropping Table [SalesLT].[ProductModelProductDescription]...';


GO
DROP TABLE [SalesLT].[ProductModelProductDescription];


GO
PRINT N'Dropping Table [SalesLT].[ProductDescription]...';


GO
DROP TABLE [SalesLT].[ProductDescription];


GO
PRINT N'Dropping View [SalesLT].[vProductModelCatalogDescription]...';


GO
DROP VIEW [SalesLT].[vProductModelCatalogDescription];


GO
PRINT N'Dropping View [School].[vScoresMath]...';


GO
DROP VIEW [School].[vScoresMath];


GO
PRINT N'Dropping Table [SalesLT].[Product]...';


GO
DROP TABLE [SalesLT].[Product];


GO
PRINT N'Dropping Table [SalesLT].[ProductCategory]...';


GO
DROP TABLE [SalesLT].[ProductCategory];


GO
PRINT N'Dropping Table [SalesLT].[ProductModel]...';


GO
DROP TABLE [SalesLT].[ProductModel];


GO
PRINT N'Dropping Procedure [School].[procPupilsAndScores]...';


GO
DROP PROCEDURE [School].[procPupilsAndScores];


GO
PRINT N'Dropping Procedure [dbo].[uspLogError]...';


GO
DROP PROCEDURE [dbo].[uspLogError];


GO
PRINT N'Dropping Procedure [dbo].[uspPrintError]...';


GO
DROP PROCEDURE [dbo].[uspPrintError];


GO
PRINT N'Dropping Table [School].[Scores]...';


GO
DROP TABLE [School].[Scores];


GO
PRINT N'Dropping Table [School].[Pupils]...';


GO
DROP TABLE [School].[Pupils];


GO
PRINT N'Dropping Table [dbo].[ErrorLog]...';


GO
DROP TABLE [dbo].[ErrorLog];


GO
PRINT N'Dropping User-Defined Data Type [dbo].[AccountNumber]...';


GO
DROP TYPE [dbo].[AccountNumber];


GO
PRINT N'Dropping User-Defined Data Type [dbo].[Flag]...';


GO
DROP TYPE [dbo].[Flag];


GO
PRINT N'Dropping User-Defined Data Type [dbo].[Name]...';


GO
DROP TYPE [dbo].[Name];


GO
PRINT N'Dropping User-Defined Data Type [dbo].[NameStyle]...';


GO
DROP TYPE [dbo].[NameStyle];


GO
PRINT N'Dropping User-Defined Data Type [dbo].[OrderNumber]...';


GO
DROP TYPE [dbo].[OrderNumber];


GO
PRINT N'Dropping User-Defined Data Type [dbo].[Phone]...';


GO
DROP TYPE [dbo].[Phone];


GO
PRINT N'Dropping Sequence [SalesLT].[SalesOrderNumber]...';


GO
DROP SEQUENCE [SalesLT].[SalesOrderNumber];


GO
PRINT N'Dropping Sequence [dbo].[seqScoreID]...';


GO
DROP SEQUENCE [dbo].[seqScoreID];


GO
PRINT N'Dropping Sequence [dbo].[seqScoresID]...';


GO
DROP SEQUENCE [dbo].[seqScoresID];


GO
PRINT N'Dropping Partition Scheme [PS_ScoresRange]...';


GO
DROP PARTITION SCHEME [PS_ScoresRange];


GO
PRINT N'Dropping Partition Function [PF_ScoresRange]...';


GO
DROP PARTITION FUNCTION [PF_ScoresRange];


GO
PRINT N'Dropping Schema [Graph]...';


GO
DROP SCHEMA [Graph];


GO
PRINT N'Dropping Schema [SalesLT]...';


GO
DROP SCHEMA [SalesLT];


GO
PRINT N'Dropping Schema [School]...';


GO
DROP SCHEMA [School];


GO
PRINT N'Altering Table [dbo].[tblTest]...';


GO
ALTER TABLE [dbo].[tblTest] DROP COLUMN [Notes];


GO
ALTER TABLE [dbo].[tblTest] ALTER COLUMN [Description] NVARCHAR (101) NOT NULL;


GO
PRINT N'Update complete.';


GO
